### ISSUE TITLE
Fix lucide icons again for prod

### ISSUE THREAD

**Issue by RealZone22** [CyanFox-Labs/CyanFox-Base#443]
Functional Code
```css
@font-face {
    font-family: "lucide";
    src: url('lucide-static/font/lucide.eot'); /* IE9*/
    src: url('lucide-static/font/lucide.eot#iefix') format('embedded-opentype'), /* IE6-IE8 */
    url("lucide-static/font/lucide.woff2") format("woff2"),
    url("lucide-static/font/lucide.woff") format("woff"),
    url('lucide-static/font/lucide.ttf') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
    url('lucide-static/font/lucide.svg#lucide') format('svg'); /* iOS 4.1- */
}
```
